# Generated by Django 5.2.7 on 2025-10-21 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("AFFECTED_AREA", "Affected Area"),
                            ("ROOT_CAUSE", "Root Cause"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "tag_type")},
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Mitigated", "Mitigated"),
                            ("Postmortem", "Postmortem"),
                            ("Actions Pending", "Actions Pending"),
                            ("Done", "Done"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                            ("P4", "P4"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_as_captain",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incidents_as_participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_as_reporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affected_area_tags",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"tag_type": "AFFECTED_AREA"},
                        related_name="incidents_by_affected_area",
                        to="incidents.tag",
                    ),
                ),
                (
                    "root_cause_tags",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"tag_type": "ROOT_CAUSE"},
                        related_name="incidents_by_root_cause",
                        to="incidents.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("SLACK", "Slack"),
                            ("JIRA", "Jira"),
                            ("DATADOG", "Datadog"),
                            ("PAGERDUTY", "PagerDuty"),
                            ("STATUSPAGE", "StatusPage"),
                            ("NOTION", "Notion"),
                            ("LINEAR", "Linear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "unique_together": {("incident", "link_type")},
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "-created_at"], name="incidents_i_status_3b7181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="incidents_i_severit_5e28cd_idx",
            ),
        ),
    ]
