# Generated by Django 5.2.7 on 2025-10-21 16:33

from django.db import migrations


def set_sequence_start(apps, schema_editor):
    """Set the incident ID sequence to start at 2000 (PostgreSQL)"""
    schema_editor.execute("SELECT setval('incidents_incident_id_seq', 2000, false);")


def reverse_sequence(apps, schema_editor):
    """Reset sequence to 1 on migration rollback"""
    schema_editor.execute("SELECT setval('incidents_incident_id_seq', 1, false);")


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_sequence_start, reverse_sequence),
    ]
