# Generated by Django 5.2.7 on 2025-10-21 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_set_incident_sequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="root_cause",
        ),
    ]
