# Generated by Django 5.2.7 on 2025-10-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0003_remove_root_cause_text_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externallink",
            old_name="link_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_type",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "type")},
        ),
        migrations.AlterField(
            model_name="incident",
            name="affected_area_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "AFFECTED_AREA"},
                related_name="incidents_by_affected_area",
                to="incidents.tag",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="root_cause_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "ROOT_CAUSE"},
                related_name="incidents_by_root_cause",
                to="incidents.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externallink",
            unique_together={("incident", "type")},
        ),
    ]
