# Generated by Django 5.2.7 on 2025-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_rename_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="participants_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
