# Generated by Django 5.2.7 on 2025-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_incident_participants_last_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="time_detected",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_diagnosed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_mitigated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_recovered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
