# Generated by Django 5.2.7 on 2025-12-15 12:59

from django.db import migrations, models


def migrate_actions_pending_to_done(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.filter(status="Actions Pending").update(status="Done")


def migrate_done_to_actions_pending(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_incident_participants_last_synced_at"),
    ]

    operations = [
        migrations.RunPython(
            migrate_actions_pending_to_done,
            migrate_done_to_actions_pending,
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Mitigated", "Mitigated"),
                    ("Postmortem", "Postmortem"),
                    ("Done", "Done"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
