# Generated by Django 5.2.7 on 2025-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_remove_actions_pending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="time_detected",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_analyzed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_mitigated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_recovered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFFECTED_AREA", "Affected Area"),
                    ("ROOT_CAUSE", "Root Cause"),
                    ("IMPACT", "Impact"),
                ],
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="incident",
            old_name="impact",
            new_name="impact_summary",
        ),
        migrations.AddField(
            model_name="incident",
            name="impact_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "IMPACT"},
                related_name="incidents_by_impact",
                to="incidents.tag",
            ),
        ),
    ]
