# Generated by Django 5.2.7 on 2026-01-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_rename_affected_area_to_affected_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="affected_region_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "AFFECTED_REGION"},
                related_name="incidents_by_affected_region",
                to="incidents.tag",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="affected_service_tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "AFFECTED_SERVICE"},
                related_name="incidents_by_affected_service",
                to="incidents.tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFFECTED_SERVICE", "Affected Service"),
                    ("AFFECTED_REGION", "Affected Region"),
                    ("ROOT_CAUSE", "Root Cause"),
                    ("IMPACT_TYPE", "Impact Type"),
                ],
                max_length=20,
            ),
        ),
    ]
