# Generated by Django 5.2.7 on 2026-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0010_add_affected_region_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallink",
            name="type",
            field=models.CharField(
                choices=[
                    ("SLACK", "Slack"),
                    ("JIRA", "Jira"),
                    ("DATADOG", "Datadog"),
                    ("PAGERDUTY", "PagerDuty"),
                    ("STATUSPAGE", "Statuspage"),
                    ("NOTION", "Notion"),
                    ("LINEAR", "Linear"),
                ],
                max_length=20,
            ),
        ),
    ]
