# Generated by Django 5.2.7 on 2026-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0011_alter_externallink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Mitigated", "Mitigated"),
                    ("Postmortem", "Postmortem"),
                    ("Done", "Done"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
