# Generated by Django 5.2.7 on 2026-01-23 16:49

from django.db import migrations, models


def approve_existing_tags(apps, schema_editor):
    Tag = apps.get_model("incidents", "Tag")
    Tag.objects.all().update(approved=True)


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0012_alter_incident_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_tags, migrations.RunPython.noop),
    ]
