# Generated by Django 5.2.11 on 2026-02-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_seed_region_tags'),
        ('incidents', '0013_add_tag_approved_field'),
    ]

    operations = [
    ]
