# Generated by Django 5.2.11 on 2026-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_add_tag_approved_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='total_downtime',
            field=models.IntegerField(blank=True, help_text='Total downtime in minutes', null=True),
        ),
    ]
