# Generated by Django 5.2.12 on 2026-04-01 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0014_add_total_downtime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="action_items_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="linear_parent_issue_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linear_issue_id", models.CharField(max_length=255, unique=True)),
                ("linear_identifier", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Todo", "Todo"),
                            ("In Progress", "In Progress"),
                            ("Done", "Done"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Todo",
                        max_length=20,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("child", "Child"),
                            ("related", "Related"),
                            ("blocked_by", "Blocked By"),
                            ("blocks", "Blocks"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="child",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
