# Generated by Django 5.2.14 on 2026-05-15 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0016_schedule_demo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_all_incident_statuses",
                        "Can view status of all incidents, including private",
                    )
                ],
            },
        ),
    ]
