# Generated by Django 6.0.1 on 2026-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0013_add_tag_approved_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="total_downtime",
            field=models.IntegerField(
                blank=True, help_text="Total downtime in seconds", null=True
            ),
        ),
    ]
