# Generated by Django 5.2.14 on 2026-05-25 17:12

from django.db import migrations, models


def fix_cancelled_spelling(apps, schema_editor):
    ActionItem = apps.get_model("incidents", "ActionItem")
    ActionItem.objects.filter(status="Cancelled").update(status="Canceled")
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.filter(status="Cancelled").update(status="Canceled")


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0018_add_action_item_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(fix_cancelled_spelling, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="actionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Todo", "Todo"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                    ("Canceled", "Canceled"),
                ],
                default="Todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Mitigated", "Mitigated"),
                    ("Postmortem", "Postmortem"),
                    ("Done", "Done"),
                    ("Canceled", "Canceled"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
