# Generated by Django 5.2.14 on 2026-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0019_canceled_and_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallink",
            name="type",
            field=models.CharField(
                choices=[
                    ("SLACK", "Slack"),
                    ("SLACK_STATUS", "Slack Status"),
                    ("JIRA", "Jira"),
                    ("DATADOG", "Datadog"),
                    ("PAGERDUTY", "PagerDuty"),
                    ("STATUSPAGE", "Statuspage"),
                    ("NOTION", "Notion"),
                    ("NOTION_TROUBLESHOOTING", "Notion Troubleshooting"),
                    ("LINEAR", "Linear"),
                ],
                max_length=30,
            ),
        ),
    ]
