# Generated by Django 5.2.14 on 2026-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0021_schedule_action_item_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="last_nag",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
