# Generated by Django 5.2.14 on 2026-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_actionitem_last_nag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_channel_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                            ("P4", "P4"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("impact_summary", models.TextField(blank=True, default="")),
                ("is_private", models.BooleanField(default=False)),
                (
                    "captain_slack_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reporter_slack_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "incidents_pending_incident",
                "ordering": ["created_at"],
            },
        ),
    ]
