# Generated by Django 5.2.14 on 2026-06-11 19:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_actionitem_last_nag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("type"),
                name="unique_tag_name_lower_type",
            ),
        ),
    ]
