# Generated by Django 5.2.14 on 2026-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_actionitem_last_nag"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="feed_message_ts",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
