# Generated by Django 5.2.16 on 2026-08-20 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0023_add_meeting_recording_link_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("INTERNAL", "Firetower"),
                            ("STATUSPAGE", "Statuspage"),
                            ("PAGERDUTY", "PagerDuty"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("incident_created", "Incident created"),
                            ("status_changed", "Status changed"),
                            ("severity_changed", "Severity changed"),
                            ("captain_changed", "Captain changed"),
                            ("title_changed", "Title changed"),
                            ("visibility_changed", "Visibility changed"),
                            (
                                "statuspage_incident_created",
                                "Statuspage incident created",
                            ),
                            ("statuspage_update_posted", "Statuspage update posted"),
                            (
                                "pagerduty_incident_triggered",
                                "PagerDuty incident triggered",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("link_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_events_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
    ]
