"""
Django settings for firetower project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

Hot reload
----------
Every config-derived setting below is produced by ``_build_config_settings`` so
the same mapping is used at import time and when ``config.toml`` changes on disk.
``apply_config`` re-applies those values onto the live settings object; the
watcher that calls it lives in ``firetower.config_reload`` and is started per
process from ``IncidentsConfig.ready`` (see ``CONFIG_WATCH_ENABLED``).
"""

import logging
import logging.config
import os
import sys
from pathlib import Path
from typing import Any, TypedDict

import sentry_sdk
from corsheaders.defaults import default_headers
from datadog import initialize
from datadog.dogstatsd.base import statsd

from firetower.config import ConfigFile, DummyConfigFile

logger = logging.getLogger(__name__)


def env_is_dev() -> bool:
    return os.environ.get("DJANGO_ENV", "dev") == "dev"


def cmd_needs_dummy_config() -> bool:
    cmds = ["collectstatic", "mypy"]
    for arg in sys.argv:
        for cmd in cmds:
            if cmd in arg:
                return True
    return False


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from TOML file
# Set CONFIG_FILE_PATH environment variable to override default location
# Hack: There are a few things that load settings.py where we don't expect to have a working config.toml.
CONFIG_FILE_PATH = os.environ.get("CONFIG_FILE_PATH", BASE_DIR.parent / "config.toml")


def _coerce_region_grouping(raw: list[Any]) -> list[list[str]]:
    if not raw:
        return []
    if isinstance(raw[0], str):
        return [list(raw)]
    return [list(g) for g in raw]


class SlackSettings(TypedDict):
    BOT_TOKEN: str
    TEAM_ID: str
    APP_TOKEN: str
    INCIDENT_FEED_CHANNEL_ID: str
    ALWAYS_INVITED_IDS: list[str]
    INCIDENT_GUIDE_MESSAGE: str
    SLASH_COMMAND: str


class StatuspageSettings(TypedDict):
    API_KEY: str
    PAGE_ID: str
    URL: str
    INITIAL_REMINDER_DELAY_MINUTES: int | None
    FOLLOWUP_REMINDER_DELAY_MINUTES: int | None
    WARNING_BUFFER_MINUTES: int


def _build_logging(config: ConfigFile) -> dict[str, Any]:
    log_level = os.environ.get("DJANGO_LOG_LEVEL", config.log_level)
    # Validate here, in the build phase, so a bad level fails before apply_config
    # mutates anything rather than making the later dictConfig() call raise
    # mid-reload and leave settings partially applied.
    if log_level not in logging.getLevelNamesMapping():
        raise ValueError(
            f"Invalid log level {log_level!r}; expected one of "
            f"{sorted(logging.getLevelNamesMapping())}"
        )
    return {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {name} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": log_level,
        },
        "loggers": {
            "firetower": {
                "handlers": ["console"],
                "level": log_level,
                "propagate": False,
            },
        },
    }


def _build_config_settings(config: ConfigFile) -> dict[str, Any]:
    """
    Compute every Django setting derived from ``config.toml``.

    This is the single source of truth shared by the module-level assignments
    below and the hot-reload path in ``apply_config``. It performs validation
    that must fail before any settings are mutated, so a bad reload leaves the
    running process untouched.
    """
    if config.auth.iap_enabled and not config.auth.iap_audience:
        raise ValueError(
            "IAP_AUDIENCE must be set when IAP is enabled. "
            "Set the iap_audience value in the configuration file."
        )

    slack: SlackSettings = {
        "BOT_TOKEN": config.slack.bot_token,
        "TEAM_ID": config.slack.team_id,
        "APP_TOKEN": config.slack.app_token,
        "INCIDENT_FEED_CHANNEL_ID": config.slack.incident_feed_channel_id,
        "ALWAYS_INVITED_IDS": config.slack.always_invited_ids,
        "INCIDENT_GUIDE_MESSAGE": config.slack.incident_guide_message,
        "SLASH_COMMAND": config.slack.slash_command,
    }

    statuspage: StatuspageSettings | None = (
        {
            "API_KEY": config.statuspage.api_key,
            "PAGE_ID": config.statuspage.page_id,
            "URL": config.statuspage.url,
            "INITIAL_REMINDER_DELAY_MINUTES": config.statuspage.initial_reminder_delay_minutes,
            "FOLLOWUP_REMINDER_DELAY_MINUTES": config.statuspage.followup_reminder_delay_minutes,
            "WARNING_BUFFER_MINUTES": config.statuspage.warning_buffer_minutes,
        }
        if config.statuspage
        else None
    )

    notion: dict | None = (
        {
            "INTEGRATION_TOKEN": config.notion.integration_token,
            "DATABASE_ID": config.notion.database_id,
            "TEMPLATE_MARKDOWN": config.notion.template_markdown,
            "TROUBLESHOOTING_DATABASE_ID": config.notion.troubleshooting_database_id,
            "TROUBLESHOOTING_TEMPLATE_MARKDOWN": config.notion.troubleshooting_template_markdown,
        }
        if config.notion
        else None
    )

    genai: dict | None = {"MODEL": config.genai.model} if config.genai else None

    pagerduty: dict | None = (
        {
            "API_TOKEN": config.pagerduty.api_token,
            "ESCALATION_POLICIES": {
                name: {
                    "id": policy.id,
                    "integration_key": policy.integration_key,
                }
                for name, policy in config.pagerduty.escalation_policies.items()
            },
        }
        if config.pagerduty
        else None
    )

    linear: dict | None = (
        {
            "CLIENT_ID": config.linear.client_id,
            "CLIENT_SECRET": config.linear.client_secret,
            "API_KEY": config.linear.api_key,
            "TEAM_ID": config.linear.team_id,
            "PROJECT_ID": config.linear.project_id,
            "SYNC_IDENTIFIERS": config.linear.sync_identifiers,
            "INCIDENT_ADOPT_ON_CREATE": config.linear.adopt_on_create,
            "ACTION_ITEM_SLO_DAYS_HIGH_PRIORITY": config.linear.action_item_slo_days_high_priority,
            "ACTION_ITEM_SLO_DAYS_MEDIUM_PRIORITY": config.linear.action_item_slo_days_medium_priority,
            "ACTION_ITEM_NAG_COMMENT_HIGH_PRIORITY": config.linear.action_item_nag_comment_high_priority,
            "ACTION_ITEM_NAG_COMMENT_MEDIUM_PRIORITY": config.linear.action_item_nag_comment_medium_priority,
            "PARENT_STATUS_COMMENT_COMPLETED": config.linear.parent_status_comment_completed,
            "PARENT_STATUS_COMMENT_STARTED": config.linear.parent_status_comment_started,
        }
        if config.linear
        else None
    )

    return {
        "CONFIG": config,
        "PROJECT_KEY": config.project_key,
        "REGION_GROUPING": _coerce_region_grouping(config.region_grouping),
        "FIRETOWER_BASE_URL": config.firetower_base_url,
        "SERVICE_REGISTRY_URL": config.service_registry_url,
        # django-fernet-encrypted-fields: `salt_keys` (plural) takes precedence
        # for key rotation; otherwise fall back to the single `salt_key`.
        "SECRET_KEY": config.django_secret_key,
        "SALT_KEY": config.salt_keys if config.salt_keys else config.salt_key,
        "DATABASES": {
            "default": {
                # Custom backend: extends the stock postgresql backend to retry
                # auth with FALLBACK_PASSWORDS during a password rotation.
                "ENGINE": "firetower.db_backend",
                "NAME": config.postgres.db,
                "HOST": config.postgres.host,
                "USER": config.postgres.user,
                "PASSWORD": config.postgres.password,
                "FALLBACK_PASSWORDS": config.postgres.fallback_passwords,
                "CONN_HEALTH_CHECKS": True,
            },
        },
        "SLACK": slack,
        "PARTICIPANT_SYNC_THROTTLE_SECONDS": int(
            config.slack.participant_sync_throttle_seconds
        ),
        "STATUSPAGE": statuspage,
        "NOTION": notion,
        "GENAI": genai,
        "HOOKS_ENABLED": config.hooks_enabled,
        "PAGERDUTY": pagerduty,
        "LINEAR": linear,
        "ACTION_ITEM_SYNC_THROTTLE_SECONDS": (
            int(config.linear.action_item_sync_throttle_seconds)
            if config.linear
            else 300
        ),
        # Tight timeout/retry budget for the incident allocation path, which
        # calls Linear while holding a DB lock. Kept lower than the default
        # LinearService budget so a hung Linear can't hold the lock for the full
        # default duration.
        "INCIDENT_ALLOC_LINEAR_TIMEOUT": (
            int(config.linear.alloc_timeout_seconds) if config.linear else 8
        ),
        "INCIDENT_ALLOC_LINEAR_RETRIES": (
            int(config.linear.alloc_max_retries) if config.linear else 1
        ),
        "IAP_ENABLED": config.auth.iap_enabled,
        "IAP_AUDIENCE": config.auth.iap_audience,
        "LOGGING": _build_logging(config),
    }


def _init_sentry(config: ConfigFile) -> None:
    """
    Initialize the Sentry SDK. Boot-only.

    Deliberately NOT called on config reload: re-running ``sentry_sdk.init`` on
    an already-initialized process is unsupported and can leave the SDK in a bad
    state, so ``sentry_dsn`` changes require a restart to take effect.
    """
    if not env_is_dev():
        sentry_sdk.init(
            dsn=config.sentry_dsn,
            send_default_pii=False,
            environment=os.environ.get("DJANGO_ENV", "unknown"),
            traces_sample_rate=1.0,
            profiles_sample_rate=0.25,
            enable_logs=True,
            trace_propagation_targets=[],
            _experiments={
                "trace_lifecycle": "stream",
            },
        )


def _apply_config_side_effects(config: ConfigFile) -> None:
    """
    Run config-derived side effects that are safe to re-run on every reload.

    These initialize global SDK clients rather than setting Django settings.
    Sentry is excluded (see ``_init_sentry``) because re-initializing it is
    unsupported.
    """
    # Initialize Datadog statsd (only when DD agent is available)
    if os.environ.get("DD_API_KEY"):
        initialize(
            statsd_host=os.environ.get("DATADOG_STATSD_HOST", "localhost"),
            statsd_port=int(os.environ.get("DATADOG_STATSD_PORT", "8125")),
            api_key=os.environ.get("DD_API_KEY"),
            app_key=os.environ.get("DD_APP_KEY"),
            statsd_namespace="firetower",
        )
        statsd.constant_tags = [
            f"env:{'production' if os.environ.get('DJANGO_ENV') == 'prod' else 'test'}",
            "service:firetower",
            f"version:{os.environ.get('K_REVISION', 'unknown')}",
        ]


def _reset_encrypted_field_caches() -> None:
    """
    Drop cached derived keys on every encrypted model field.

    django-fernet-encrypted-fields derives its Fernet keys from SALT_KEY /
    SECRET_KEY and caches them (plus the resulting Fernet/MultiFernet) in
    ``@cached_property`` attributes (``keys``/``f``) on each field instance.
    Those field instances live for the whole process, so without busting the
    cache a reloaded SALT_KEY/SECRET_KEY is silently ignored by encryption and
    decryption until restart — even though ``settings.SALT_KEY`` reports the new
    value. That is especially dangerous during salt rotation: adding a key would
    appear applied while ``MultiFernet`` still only used the old one.

    Re-derivation is deferred (the cached_property recomputes lazily on next
    access) and deterministic, so busting mid-request is safe.
    """
    from django.apps import apps  # noqa: PLC0415
    from encrypted_fields.fields import EncryptedFieldMixin  # noqa: PLC0415

    for model in apps.get_models():
        for field in model._meta.get_fields():
            if isinstance(field, EncryptedFieldMixin):
                field.__dict__.pop("keys", None)
                field.__dict__.pop("f", None)


def apply_config(config: ConfigFile) -> None:
    """
    Re-apply every config-derived value onto the live Django settings object.

    Used by the hot-reload watcher (``firetower.config_reload``). Applied in two
    phases so a reload is atomic:

    1. Build and validate everything that can raise (the settings values, the
       normalized DATABASES for the connection handler, and the Datadog
       re-init) *before* touching any global state. A bad ``config.toml`` aborts
       here, leaving the running process entirely on its previous config.
    2. Commit: rebind settings, apply logging, swap the connection handler's
       cached settings, and (when SALT_KEY/SECRET_KEY changed) bust the
       encrypted-field key caches. These steps are constructed not to raise, so
       settings, logging, the DB connection handler and the crypto keys move
       together — never leaving, say, ``settings.DATABASES`` updated while the
       connection handler still serves the old config.

    Each setting is rebound wholesale; the GIL makes a single ``setattr`` atomic,
    so concurrent readers see either the old or the new value, never a torn one.
    """
    from django.conf import settings as live_settings  # noqa: PLC0415
    from django.db import connections  # noqa: PLC0415

    # --- Phase 1: build and validate. No global state is mutated here. ---
    values = _build_config_settings(config)
    # Normalize/validate the DB config up front (raises if malformed, e.g. no
    # 'default'). configure_settings mutates in place and returns the same dict,
    # so settings.DATABASES and the connection handler end up sharing one
    # identical, fully-defaulted object, exactly as Django wires them itself.
    new_connection_settings = connections.configure_settings(values["DATABASES"])
    # Datadog re-init is a global side effect with no dependency on the new
    # settings, so run it in this phase: if it fails, nothing else has changed.
    _apply_config_side_effects(config)
    # Whether the encryption inputs changed; captured before the settings are
    # rebound so we can bust the encrypted-field key caches only when needed
    # (re-derivation is comparatively expensive: PBKDF2 with 100k iterations).
    crypto_changed = (
        getattr(live_settings, "SALT_KEY", None) != values["SALT_KEY"]
        or getattr(live_settings, "SECRET_KEY", None) != values["SECRET_KEY"]
    )

    # --- Phase 2: commit. These steps must not raise. ---
    for key, value in values.items():
        setattr(live_settings, key, value)

    # DATABASES may have changed (host/name/password). Mutating settings.DATABASES
    # alone is not enough: ConnectionHandler caches it (@cached_property) and keeps
    # connections in thread-local storage. So close_all() from this watcher thread
    # would close nothing in the worker threads, and even new connections would be
    # built from the stale cached config. Swap in the handler's cached settings
    # (the same reset Django uses for CACHES) so any *new* connection uses the new
    # config; each worker thread then retires its own stale connection through the
    # normal end-of-request cycle (CONN_MAX_AGE defaults to 0) and reconnects fresh.
    # We deliberately do not force-close connections owned by other threads, which
    # is not thread-safe; in-flight requests finish on their existing connection.
    # Kept adjacent to the setattr loop (and before dictConfig) so settings and the
    # connection handler are always committed together.
    connections._settings = connections.settings = new_connection_settings

    # SALT_KEY/SECRET_KEY feed encrypted_fields' cached key derivation; bust that
    # cache so a reloaded salt/secret actually takes effect (see the helper).
    if crypto_changed:
        _reset_encrypted_field_caches()

    logging.config.dictConfig(values["LOGGING"])


config: ConfigFile = (
    DummyConfigFile()
    if cmd_needs_dummy_config()
    else ConfigFile.from_file(CONFIG_FILE_PATH)
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_is_dev()

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "::1",
    "firetower.getsentry.net",
    "test.firetower.getsentry.net",
    "firetower",
    "backend",  # name from the nginx proxy_pass
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://firetower.getsentry.net",
    "https://test.firetower.getsentry.net",
]

CORS_ALLOW_HEADERS = (
    *default_headers,
    "sentry-trace",
    "baggage",
)

CORS_ALLOW_CREDENTIALS = True

if not env_is_dev():
    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "djk8s",
    "firetower.auth",
    "firetower.incidents",
    "firetower.integrations",
    "firetower.slack_app",
    "django_q",
]

MIDDLEWARE = [
    "firetower.incidents.metrics.middleware.MetricsMiddleware",
    "djk8s.middleware.ProbeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "firetower.auth.middleware.ConditionalCsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "firetower.auth.middleware.IAPAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "firetower.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "firetower.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "backend/"
STATIC_ROOT = "static/backend/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # Authentication - use our custom class that reads from IAP middleware.
    # This bridges Django middleware user to DRF's Request.user property.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "firetower.auth.authentication.IAPAuthentication",
    ],
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": [
        "firetower.incidents.permissions.IsAuthenticated",
    ],
    # Only accept JSON - rejects form-encoded requests which bypass CORS preflight.
    # Defense in depth alongside browser third-party cookie blocking and CORS.
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    # Only render JSON - disables browsable API.
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# django-k8s proreadiness probes
DJK8S_READINESS_PROBES = [
    "djk8s.probes.DatabaseProbe",
]

Q_CLUSTER = {
    "name": "firetower",
    "orm": "default",
    "workers": 4,
    "timeout": 180,
    "retry": 210,
    "queue_limit": 50,
    "bulk": 10,
    "cache": "qcache",
}

CACHE_TABLE = "django_q_cache"
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "qcache": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": CACHE_TABLE,
    },
}

# One-shot management commands run settings + app startup but should never spawn
# the long-lived config watcher (see IncidentsConfig.ready). Detect them, and
# pytest, so only real service processes (server, slack bot, q cluster) watch.
_CONFIG_WATCH_SKIP_CMDS = {
    "migrate",
    "makemigrations",
    "collectstatic",
    "test",
    "shell",
    "dbshell",
    "createsuperuser",
    "makemessages",
    "compilemessages",
    "check",
    "showmigrations",
    "sqlmigrate",
    "dumpdata",
    "loaddata",
    "flush",
    "createcachetable",
}
CONFIG_WATCH_ENABLED = (
    not cmd_needs_dummy_config()
    and "pytest" not in sys.modules
    and not any(arg in _CONFIG_WATCH_SKIP_CMDS for arg in sys.argv)
)

# How often (seconds) the config watcher re-reads and hashes config.toml to
# detect changes. Polling is used instead of inotify because Cloud Run's gVisor
# sandbox does not deliver filesystem events.
CONFIG_WATCH_POLL_SECONDS = float(os.environ.get("CONFIG_WATCH_POLL_SECONDS", "15"))


# ---------------------------------------------------------------------------
# Config-derived settings.
#
# These are produced by ``_build_config_settings`` (the single source of truth
# shared with the hot-reload path). They are also declared here as annotated
# module-level names so the django-stubs mypy plugin can see the setting names
# and their types.
# ---------------------------------------------------------------------------
_config_settings = _build_config_settings(config)

CONFIG: ConfigFile = _config_settings["CONFIG"]
PROJECT_KEY: str = _config_settings["PROJECT_KEY"]
REGION_GROUPING: list[list[str]] = _config_settings["REGION_GROUPING"]
FIRETOWER_BASE_URL: str = _config_settings["FIRETOWER_BASE_URL"]
SERVICE_REGISTRY_URL: str | None = _config_settings["SERVICE_REGISTRY_URL"]
SECRET_KEY: str = _config_settings["SECRET_KEY"]
SALT_KEY: str | list[str] = _config_settings["SALT_KEY"]
DATABASES: dict[str, Any] = _config_settings["DATABASES"]
SLACK: SlackSettings = _config_settings["SLACK"]
PARTICIPANT_SYNC_THROTTLE_SECONDS: int = _config_settings[
    "PARTICIPANT_SYNC_THROTTLE_SECONDS"
]
STATUSPAGE: StatuspageSettings | None = _config_settings["STATUSPAGE"]
NOTION: dict | None = _config_settings["NOTION"]
GENAI: dict | None = _config_settings["GENAI"]
HOOKS_ENABLED: bool = _config_settings["HOOKS_ENABLED"]
PAGERDUTY: dict | None = _config_settings["PAGERDUTY"]
LINEAR: dict | None = _config_settings["LINEAR"]
ACTION_ITEM_SYNC_THROTTLE_SECONDS: int = _config_settings[
    "ACTION_ITEM_SYNC_THROTTLE_SECONDS"
]
INCIDENT_ALLOC_LINEAR_TIMEOUT: int = _config_settings["INCIDENT_ALLOC_LINEAR_TIMEOUT"]
INCIDENT_ALLOC_LINEAR_RETRIES: int = _config_settings["INCIDENT_ALLOC_LINEAR_RETRIES"]
IAP_ENABLED: bool = _config_settings["IAP_ENABLED"]
IAP_AUDIENCE: str | None = _config_settings["IAP_AUDIENCE"]
LOGGING: dict[str, Any] = _config_settings["LOGGING"]

_init_sentry(config)
_apply_config_side_effects(config)
