"""
Django settings for firetower project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from datadog import initialize
from datadog.dogstatsd.base import statsd

from firetower.config import ConfigFile, DummyConfigFile


def env_is_dev() -> bool:
    return os.environ.get("DJANGO_ENV", "dev") == "dev"


def cmd_needs_dummy_config() -> bool:
    cmds = ["collectstatic", "mypy"]
    for arg in sys.argv:
        for cmd in cmds:
            if cmd in arg:
                return True
    return False


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from TOML file
# Set CONFIG_FILE_PATH environment variable to override default location
# Hack: There are a few things that load settings.py where we don't expect to have a working config.toml.
CONFIG_FILE_PATH = os.environ.get("CONFIG_FILE_PATH", BASE_DIR.parent / "config.toml")
config: ConfigFile = (
    DummyConfigFile()
    if cmd_needs_dummy_config()
    else ConfigFile.from_file(CONFIG_FILE_PATH)
)


if not env_is_dev():
    import sentry_sdk

    sentry_sdk.init(
        dsn=config.sentry_dsn,
        send_default_pii=False,
        environment=os.environ.get("DJANGO_ENV", "unknown"),
    )

# Global project settings
PROJECT_KEY = config.project_key

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config.django_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_is_dev()

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "::1",
    "firetower.getsentry.net",
    "test.firetower.getsentry.net",
    "firetower",
    "backend",  # name from the nginx proxy_pass
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://firetower.getsentry.net",
    "https://*.firetower.getsentry.net",
]

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "djk8s",
    "firetower.auth",
    "firetower.incidents",
    "firetower.integrations",
]

MIDDLEWARE = [
    "firetower.incidents.metrics.middleware.MetricsMiddleware",
    "djk8s.middleware.ProbeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "firetower.auth.middleware.ConditionalCsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "firetower.auth.middleware.IAPAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "firetower.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "firetower.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config.postgres.db,
        "HOST": config.postgres.host,
        "USER": config.postgres.user,
        "PASSWORD": config.postgres.password,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "backend/"
STATIC_ROOT = "static/backend/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Jira Integration Configuration
JIRA = {
    "DOMAIN": config.jira.domain,
    "ACCOUNT": config.jira.account,
    "API_KEY": config.jira.api_key,
    "SEVERITY_FIELD": config.jira.severity_field,
}

# Slack Integration Configuration
SLACK = {
    "BOT_TOKEN": config.slack.bot_token,
    "TEAM_ID": config.slack.team_id,
}

PARTICIPANT_SYNC_THROTTLE_SECONDS = int(config.slack.participant_sync_throttle_seconds)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # Authentication - use our custom class that reads from IAP middleware.
    # This bridges Django middleware user to DRF's Request.user property.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "firetower.auth.authentication.IAPAuthentication",
    ],
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": [
        "firetower.incidents.permissions.IsAuthenticated",
    ],
    # Only accept JSON - rejects form-encoded requests which bypass CORS preflight.
    # Defense in depth alongside browser third-party cookie blocking and CORS.
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}

# Google IAP Authentication Configuration
IAP_ENABLED = config.auth.iap_enabled
IAP_AUDIENCE = config.auth.iap_audience

# Validate IAP settings in production
if IAP_ENABLED and not IAP_AUDIENCE:
    raise Exception(
        "IAP_AUDIENCE must be set when IAP is enabled in production. "
        "Set the iap_audience value in the configuration file."
    )

# django-k8s proreadiness probes
DJK8S_READINESS_PROBES = [
    "djk8s.probes.DatabaseProbe",
]

# Initialize Datadog statsd
initialize(
    statsd_host=os.environ.get("DATADOG_STATSD_HOST", "localhost"),
    statsd_port=int(os.environ.get("DATADOG_STATSD_PORT", "8125")),
    api_key=config.datadog.api_key if config.datadog else None,
    app_key=config.datadog.app_key if config.datadog else None,
    statsd_namespace="firetower",
)
statsd.constant_tags = [
    f"env:{'production' if os.environ.get('DJANGO_ENV') == 'prod' else 'test'}",
    "service:firetower",
    f"version:{os.environ.get('K_REVISION', 'unknown')}",
]

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "firetower": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
