codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: true
        target: 0%
    patch:
      default:
        informational: true
        target: 0%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
  after_n_builds: 2
