codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: true
        target: 0%
    patch:
      default:
        informational: true
        target: 0%

comment: false
