services:
  ftwr-migrate:
    image: firetower
    environment:
    - "DJANGO_SECRET_KEY=some_random_bullshit"
    - "DJANGO_PG_USER=postgres"
    - "DJANGO_PG_PASS=dummy_dev_password"
    - "DJANGO_PG_DB=firetower"
    - "DJANGO_PG_HOST=ftwr-postgres"
    - "JIRA_ACCOUNT=blah"
    - "JIRA_API_KEY=blah"
    - "JIRA_PROJECT_KEY=INC"
    - "JIRA_SEVERITY_FIELD=dummy"
    - "SLACK_BOT_TOKEN=dummy"
    - "SLACK_TEAM_ID=dummy"
    - "IAP_AUDIENCE=dummy"
    - "DJANGO_ENV=dev"
    entrypoint: [
       "/app/.venv/bin/django-admin",
       "migrate",
       "--settings", "firetower.settings",
    ]
  ftwr-postgres:
    image: postgres:17.6-alpine3.22
    environment:
    - "POSTGRES_PASSWORD=dummy_dev_password"
    - "POSTGRES_DB=firetower"
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ftwr-adminer:
    image: adminer
    environment:
    - ADMINER_DEFAULT_DRIVER=pgsql
    - ADMINER_DEFAULT_SERVER=ftwr-postgres
    - ADMINER_DEFAULT_USERNAME=postgres
    - ADMINER_DEFAULT_PASSWORD=dummy_dev_password
    - ADMINER_DEFAULT_DB=firetower
    ports:
      - 8089:8080
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
          ];
        }
        include './adminer.php';
      ?>


volumes:
  pgdata:
