/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncidentIdRouteImport } from './routes/$incidentId'
import { Route as IndexRouteImport } from './routes/index'

const IncidentIdRoute = IncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$incidentId': typeof IncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$incidentId'
  id: '__root__' | '/' | '/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentIdRoute: typeof IncidentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$incidentId': {
      id: '/$incidentId'
      path: '/$incidentId'
      fullPath: '/$incidentId'
      preLoaderRoute: typeof IncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentIdRoute: IncidentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
