# Generated by Django 5.2.7 on 2025-10-21 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firetower_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externalprofile",
            name="firetower_a_profile_8c03cc_idx",
        ),
        migrations.RenameField(
            model_name="externalprofile",
            old_name="profile_type",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="externalprofile",
            unique_together={("user", "type")},
        ),
        migrations.AddIndex(
            model_name="externalprofile",
            index=models.Index(
                fields=["type", "external_id"], name="firetower_a_type_bcf29e_idx"
            ),
        ),
    ]
