# Generated by Django 5.2.7 on 2025-10-21 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firetower_auth", "0002_rename_type_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_admin",
        ),
    ]
