# Generated by Django 5.2.7 on 2025-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firetower_auth", "0003_remove_is_admin_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalprofile",
            name="type",
            field=models.CharField(
                choices=[
                    ("IAP", "IAP"),
                    ("SLACK", "Slack"),
                    ("PAGERDUTY", "PagerDuty"),
                    ("LINEAR", "Linear"),
                    ("DATADOG", "Datadog"),
                ],
                max_length=20,
            ),
        ),
    ]
